export enum RewardType {

  TRAVELER_VERIFY = 'TRAVELER_VERIFY',

  STAY = 'STAY',

  PLACE_VERIFY = 'PLACE_VERIFY',

  COURSE_COMPLETE = 'COURSE_COMPLETE',

  CONGESTION = 'CONGESTION',

  NIGHT_EVENT = 'NIGHT_EVENT',

  CONVERT = 'CONVERT'

}